-- Basic config
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')


-- Plugins
require('plugins.neodev')
require('plugins.notify')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.nullls')
require('plugins.bufferline')
require('plugins.autopairs')
require('plugins.comments')
require('plugins.dashboard')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.whichkey')
require('plugins.toggleterm')
require('plugins.f-string-py')
require('plugins.cursorline')
require('plugins.virtcolumn')
